GRANT SELECT ON dream.AggregationGroupAssignment TO db_dreamusers
GRANT SELECT ON dream.AggregationGroupDataSet TO db_dreamusers
GRANT SELECT ON dream.AllowedMonth TO db_dreamusers
GRANT SELECT ON dream.ApplicationUser TO db_dreamusers
GRANT SELECT ON dream.AvailableFundsRetrievalDetail TO db_dreamusers
GRANT SELECT ON dream.AvailableFundsRetrievalType TO db_dreamusers
GRANT SELECT ON dream.BalanceCapAndFloorDetail TO db_dreamusers
GRANT SELECT ON dream.BalanceCapAndFloorSet TO db_dreamusers
GRANT SELECT ON dream.CollateralizedSecuritizationDataSet TO db_dreamusers
GRANT SELECT ON dream.CollateralizedSecuritizationTranche TO db_dreamusers
GRANT SELECT ON dream.CompoundingConvention TO db_dreamusers
GRANT SELECT ON dream.DayCountConvention TO db_dreamusers
GRANT SELECT ON dream.FeeDetail TO db_dreamusers
GRANT SELECT ON dream.FeeGroupDetail TO db_dreamusers
GRANT SELECT ON dream.FundsDistributionType TO db_dreamusers
GRANT SELECT ON dream.MarketData TO db_dreamusers
GRANT SELECT ON dream.MarketDataSet TO db_dreamusers
GRANT SELECT ON dream.MarketDataType TO db_dreamusers
GRANT SELECT ON dream.MarketRateEnvironment TO db_dreamusers
GRANT SELECT ON dream.PaceAssessmentRatePlan TO db_dreamusers
GRANT SELECT ON dream.PaceAssessmentRatePlanTermSet TO db_dreamusers
GRANT SELECT ON dream.PaceAssessmentRecord TO db_dreamusers
GRANT SELECT ON dream.PaceAssessmentRecordDataSet TO db_dreamusers
GRANT SELECT ON dream.PaymentConvention TO db_dreamusers
GRANT SELECT ON dream.PerformanceAssumptionAssignment TO db_dreamusers
GRANT SELECT ON dream.PerformanceAssumptionDataSet TO db_dreamusers
GRANT SELECT ON dream.PerformanceAssumptionType TO db_dreamusers
GRANT SELECT ON dream.PrepaymentPenaltyPlan TO db_dreamusers
GRANT SELECT ON dream.PrepaymentPenaltyPlanDetail TO db_dreamusers
GRANT SELECT ON dream.PricingGroupAssignment TO db_dreamusers
GRANT SELECT ON dream.PricingGroupDataSet TO db_dreamusers
GRANT SELECT ON dream.PricingType TO db_dreamusers
GRANT SELECT ON dream.PriorityOfPaymentsAssignment TO db_dreamusers
GRANT SELECT ON dream.PriorityOfPaymentsSet TO db_dreamusers
GRANT SELECT ON dream.RateCurveData TO db_dreamusers
GRANT SELECT ON dream.RateCurveDataSet TO db_dreamusers
GRANT SELECT ON dream.RateIndex TO db_dreamusers
GRANT SELECT ON dream.RateIndexGroup TO db_dreamusers
GRANT SELECT ON dream.RedemptionLogicAllowedMonthsDetail TO db_dreamusers
GRANT SELECT ON dream.RedemptionLogicAllowedMonthsSet TO db_dreamusers
GRANT SELECT ON dream.RedemptionLogicDataSet TO db_dreamusers
GRANT SELECT ON dream.RedemptionLogicType TO db_dreamusers
GRANT SELECT ON dream.RedemptionTranchesDetail TO db_dreamusers
GRANT SELECT ON dream.RedemptionTranchesSet TO db_dreamusers
GRANT SELECT ON dream.ReserveAccountsDetail TO db_dreamusers
GRANT SELECT ON dream.ReserveAccountsSet TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysis TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysisComment TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysisDataSet TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysisInput TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysisOwner TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysisResult TO db_dreamusers
GRANT SELECT ON dream.SecuritizationAnalysisSummary TO db_dreamusers
GRANT SELECT ON dream.SecuritizationInputType TO db_dreamusers
GRANT SELECT ON dream.SecuritizationNode TO db_dreamusers
GRANT SELECT ON dream.SecuritizationNodeDataSet TO db_dreamusers
GRANT SELECT ON dream.SecuritizationResultType TO db_dreamusers
GRANT SELECT ON dream.TrancheCashFlowType TO db_dreamusers
GRANT SELECT ON dream.TrancheCoupon TO db_dreamusers
GRANT SELECT ON dream.TrancheDetail TO db_dreamusers
GRANT SELECT ON dream.TrancheType TO db_dreamusers
GRANT SELECT ON dream.Vector TO db_dreamusers
GRANT SELECT ON dream.VectorParent TO db_dreamusers