GRANT EXECUTE ON dream.InsertAggregationGroupAssignment TO db_dreamusers
GRANT EXECUTE ON dream.InsertAggregationGroupDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertAvailableFundsRetrievalDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertBalanceCapAndFloorDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertBalanceCapAndFloorSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertCollateralizedSecuritizationDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertCollateralizedSecuritizationTranche TO db_dreamusers
GRANT EXECUTE ON dream.InsertFeeDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertFeeGroupDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertMarketData TO db_dreamusers
GRANT EXECUTE ON dream.InsertMarketDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertMarketRateEnvironment TO db_dreamusers
GRANT EXECUTE ON dream.InsertPaceAssessmentRatePlan TO db_dreamusers
GRANT EXECUTE ON dream.InsertPaceAssessmentRatePlanTermSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertPaceAssessmentRecord TO db_dreamusers
GRANT EXECUTE ON dream.InsertPaceAssessmentRecordDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertPerformanceAssumptionAssignment TO db_dreamusers
GRANT EXECUTE ON dream.InsertPerformanceAssumptionDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertPrepaymentPenaltyPlan TO db_dreamusers
GRANT EXECUTE ON dream.InsertPrepaymentPenaltyPlanDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertPricingGroupAssignment TO db_dreamusers
GRANT EXECUTE ON dream.InsertPricingGroupDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertPriorityOfPaymentsAssignment TO db_dreamusers
GRANT EXECUTE ON dream.InsertPriorityOfPaymentsSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertRateCurveData TO db_dreamusers
GRANT EXECUTE ON dream.InsertRateCurveDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertRedemptionLogicAllowedMonthsDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertRedemptionLogicAllowedMonthsSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertRedemptionLogicDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertRedemptionTranchesDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertRedemptionTranchesSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertReserveAccountsDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertReserveAccountsSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysis TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysisComment TO db_dreamusers
GRANT EXECUTE ON dream.UpdateSecuritizationAnalysisComment TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysisDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysisInput TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysisOwner TO db_dreamusers
GRANT EXECUTE ON dream.UpdateSecuritizationAnalysisOwner TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysisResult TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationAnalysisSummary TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationNode TO db_dreamusers
GRANT EXECUTE ON dream.InsertSecuritizationNodeDataSet TO db_dreamusers
GRANT EXECUTE ON dream.InsertTrancheCoupon TO db_dreamusers
GRANT EXECUTE ON dream.InsertTrancheDetail TO db_dreamusers
GRANT EXECUTE ON dream.InsertVector TO db_dreamusers
GRANT EXECUTE ON dream.InsertVectorParent TO db_dreamusers