exec dream.InsertPerformanceAssumptionType 'Conditional Prepayment Rate', 'CPR'
exec dream.InsertPerformanceAssumptionType 'Single Monthly Mortality', 'SMM'
exec dream.InsertPerformanceAssumptionType 'Conditional Default Rate', 'CDR'
exec dream.InsertPerformanceAssumptionType 'Monthly Default Rate', 'MDR'
exec dream.InsertPerformanceAssumptionType 'Loss Given Default', 'LGD'
exec dream.InsertPerformanceAssumptionType 'Monthly Delinquency Rate', 'DQ'