exec dream.InsertSecuritizationInputType 'Aggregation Groupings'
exec dream.InsertSecuritizationInputType 'Performance Assumptions'
exec dream.InsertSecuritizationInputType 'Pricing Assumption Groupings'
exec dream.InsertSecuritizationInputType 'Market Rate Environment'
exec dream.InsertSecuritizationInputType 'PACE Assessment Collateral'
exec dream.InsertSecuritizationInputType 'Collateralized Securitizations'
exec dream.InsertSecuritizationInputType 'Priority of Payments'
exec dream.InsertSecuritizationInputType 'Redemption Logic'
exec dream.InsertSecuritizationInputType 'Securitization Nodes Structure'
exec dream.InsertSecuritizationInputType 'Securitization Analysis Input'