exec dream.InsertTrancheCashFlowType 'Payment'
exec dream.InsertTrancheCashFlowType 'Payment Shortfall'
exec dream.InsertTrancheCashFlowType 'Principal'
exec dream.InsertTrancheCashFlowType 'Principal Shortfall'
exec dream.InsertTrancheCashFlowType 'Interest'
exec dream.InsertTrancheCashFlowType 'Interest Shortfall'
exec dream.InsertTrancheCashFlowType 'Fees'
exec dream.InsertTrancheCashFlowType 'Fees Shortfall'
exec dream.InsertTrancheCashFlowType 'Reserves'
