//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dream.IO.Database {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class DatabaseConnection : global::System.Configuration.ApplicationSettingsBase {
        
        private static DatabaseConnection defaultInstance = ((DatabaseConnection)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DatabaseConnection())));
        
        public static DatabaseConnection Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AWSSQLBIDEV01")]
        public string SecuritizationEngineServerName {
            get {
                return ((string)(this["SecuritizationEngineServerName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CapitalMarkets")]
        public string SecuritizationEngineDatabaseName {
            get {
                return ((string)(this["SecuritizationEngineDatabaseName"]));
            }
            set {
                this["SecuritizationEngineDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AWSSQLBIDEV01")]
        public string FinanceManagementServerName {
            get {
                return ((string)(this["FinanceManagementServerName"]));
            }
            set {
                this["FinanceManagementServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RAHERODW")]
        public string FinanceManagementDatabaseName {
            get {
                return ((string)(this["FinanceManagementDatabaseName"]));
            }
            set {
                this["FinanceManagementDatabaseName"] = value;
            }
        }
    }
}
