DECLARE @Department int
DECLARE @DepartmentGroup int
DECLARE @IncomeStatementDepartment1 int
DECLARE @IncomeStatementDepartment2 int

EXEC FinanceManagement.InsertCostCenterAggregationGroup 'Department', 1
SET @Department = (SELECT MAX(CostCenterAggregationGroupId) FROM FinanceManagement.CostCenterAggregationGroup)

EXEC FinanceManagement.InsertCostCenterAggregationGroup 'Department Group', 1
SET @DepartmentGroup = (SELECT MAX(CostCenterAggregationGroupId) FROM FinanceManagement.CostCenterAggregationGroup)

EXEC FinanceManagement.InsertCostCenterAggregationGroup 'IS Department 1', 1	
SET @IncomeStatementDepartment1 = (SELECT MAX(CostCenterAggregationGroupId) FROM FinanceManagement.CostCenterAggregationGroup)

EXEC FinanceManagement.InsertCostCenterAggregationGroup 'IS Department 2', 1	
SET @IncomeStatementDepartment2 = (SELECT MAX(CostCenterAggregationGroupId) FROM FinanceManagement.CostCenterAggregationGroup)

EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 50, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 11, 'Corporate & Other'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 1, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 4, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 18, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 20, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 34, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 45, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 27, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 46, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 52, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 16, 'Facilities'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 21, 'Legal'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 31, 'Legal'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 28, 'Market Expansion and Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 30, 'Market Expansion and Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 29, 'Market Expansion and Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 7, 'Market Expansion and Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 35, 'Market Expansion and Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 23, 'Market Expansion and Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 40, 'Compliance'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 48, 'Compliance'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 49, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 14, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 2, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 12, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 51, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 24, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 39, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 47, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 6, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 53, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 37, 'Product Management'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 38, 'Product Management'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 36, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 32, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 22, 'Product Management'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 5, 'Channel & Inside Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 26, 'Channel & Inside Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 10, 'Channel & Inside Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 42, 'Channel & Inside Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 9, 'Channel & Inside Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 43, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 15, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 25, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 13, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 3, 'Business Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 19, 'Business Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 8, 'Consumer Lending'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 41, 'Consumer Lending'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 33, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 44, 'Operations'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @Department, 17, 'Corporate & Other'

EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 50, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 11, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 1, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 4, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 18, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 20, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 34, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 45, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 27, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 46, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 52, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 16, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 21, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 31, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 28, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 30, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 29, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 7, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 35, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 23, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 40, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 48, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 49, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 14, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 2, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 12, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 51, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 24, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 39, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 47, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 6, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 53, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 37, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 38, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 36, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 32, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 22, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 5, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 26, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 10, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 42, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 9, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 43, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 15, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 25, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 13, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 3, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 19, 'Cost to Acquire'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 8, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 41, 'Other OpEx'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 33, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 44, 'Cost to Produce'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @DepartmentGroup, 17, 'Other OpEx'

EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 50, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 11, 'Corporate & Other'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 1, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 4, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 18, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 20, 'Funding'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 34, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 45, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 27, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 46, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 52, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 16, 'General and Administration'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 21, 'Legal'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 31, 'Legal'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 28, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 30, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 29, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 7, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 35, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 23, 'HERO Property Advisors'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 40, 'Compliance'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 48, 'Contractor Management'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 49, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 14, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 2, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 12, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 51, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 24, 'HERO Property Advisors'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 39, 'Program Services'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 47, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 6, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 53, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 37, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 38, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 36, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 32, 'Corporate & Other'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 22, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 5, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 26, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 10, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 42, 'Contractor Support'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 9, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 43, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 15, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 25, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 13, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 3, 'Business Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 19, 'Business Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 8, 'Consumer Lending'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 41, 'Consumer Lending'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 33, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 44, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment1, 17, 'Corporate & Other'

EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 50, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 11, 'Corporate & Other'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 1, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 4, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 18, 'Finance & Accounting'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 20, 'Funding'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 34, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 45, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 27, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 46, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 52, 'People & Culture'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 16, 'Facilities'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 21, 'Legal'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 31, 'Legal'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 28, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 30, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 29, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 7, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 35, 'Market Development and External Affairs'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 23, 'HERO Property Advisors'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 40, 'Compliance'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 48, 'Contractor Management'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 49, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 14, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 2, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 12, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 51, 'Marketing'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 24, 'HERO Property Advisors'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 39, 'Program Services'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 47, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 6, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 53, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 37, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 38, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 36, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 32, 'Corporate & Other'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 22, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 5, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 26, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 10, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 42, 'Contractor Support'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 9, 'Channel Sales'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 43, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 15, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 25, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 13, 'Technology'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 3, 'Business Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 19, 'Business Development'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 8, 'Consumer Lending'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 41, 'Consumer Lending'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 33, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 44, 'Production'
EXEC FinanceManagement.InsertCostCenterAggregationGroupMapping @IncomeStatementDepartment2, 17, 'Corporate & Other'