GRANT SELECT ON FinanceManagement.CostCenterAggregationGroup TO db_grantjournallinefact
GRANT SELECT ON FinanceManagement.CostCenterAggregationGroupMapping TO db_grantjournallinefact

GRANT SELECT ON FinanceManagement.LedgerAccountAggregationGroup TO db_grantjournallinefact
GRANT SELECT ON FinanceManagement.LedgerAccountAggregationGroupMapping TO db_grantjournallinefact

GRANT SELECT ON FinanceManagement.ProductLineAggregationGroup TO db_grantjournallinefact
GRANT SELECT ON FinanceManagement.ProductLineAggregationGroupMapping TO db_grantjournallinefact

GRANT SELECT ON FinanceManagement.RegionAggregationGroup TO db_grantjournallinefact
GRANT SELECT ON FinanceManagement.RegionAggregationGroupMapping TO db_grantjournallinefact


