GRANT EXECUTE ON FinanceManagement.InsertCostCenterAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.UpdateCostCenterAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.InsertCostCenterAggregationGroupMapping TO db_grantjournallinefact

GRANT EXECUTE ON FinanceManagement.InsertLedgerAccountAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.UpdateLedgerAccountAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.InsertLedgerAccountAggregationGroupMapping TO db_grantjournallinefact

GRANT EXECUTE ON FinanceManagement.InsertProductLineAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.UpdateProductLineAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.InsertProductLineAggregationGroupMapping TO db_grantjournallinefact

GRANT EXECUTE ON FinanceManagement.InsertRegionAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.UpdateRegionAggregationGroup TO db_grantjournallinefact
GRANT EXECUTE ON FinanceManagement.InsertRegionAggregationGroupMapping TO db_grantjournallinefact


